name: Scrape
# Controls when the action will run.
on:
  schedule:
    - cron:  '0 13 * * *'
jobs: 
  autoscrape:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Setup dependencies
        run: |
          R -e 'install.packages("tidyverse")' 
          R -e 'install.packages("rvest")' 
          R -e 'install.packages("janitor")' 
          
      - name: Run scraper
        run: Rscript aaa_gas_scraper_GITHUB.R
          
    
