name: R Scraper

on:
  schedule:
    - cron: "0 8 * * *" # 8 a.m. every day UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@master
        
      - name: Setup dependencies
        run: |
          R -e 'install.packages("tidyverse")' 
          R -e 'install.packages("rvest")' 
          R -e 'install.packages("janitor")' 
          
      - name: Run scraper
      run: aaa_gas_scraper_GITHUB.R
