name: Scrape
# Controls when the action will run.
on:
  schedule:
    - cron: "0 8 * * *" # 8 a.m. every day UTC
  workflow_dispatch:
    
jobs: 
  autoscrape:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Setup dependencies
        run: |
          R -e 'install.packages("tidyverse")' 
          R -e 'install.packages("rvest")' 
          R -e 'install.packages("janitor")' 
          
      - name: Run scraper
        run: Rscript aaa_gas_scraper_GITHUB.R
        
      - name: Add and commit	
        run: |
          git add .	
          git config user.name "Automated"	
          git config user.email "actions@users.noreply.github.com"	
          git commit -m "Latest data" 	
      - name: Push	
        run: git push
