name: Scrape
# Controls when the action will run.
on:
  schedule:
    - cron: "0 19 * * *" # 7 p.m. every day UTC (11 am PST)
  workflow_dispatch:
    
jobs: 
  autoscrape:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Setup Packages
        run: |
          R -e 'install.packages("tidyverse")' 
          R -e 'install.packages("rvest")' 
          R -e 'install.packages("janitor")' 
          R -e 'install.packages("mailR")'
          R -e 'install.packages("rmarkdown")' 
          R -e 'install.packages("pandoc")' 
          R -e 'install.packages("googledrive")' 
          
      - name: Run Scraper
        run: Rscript aaa_gas_scraper_GITHUB.R
        
      - name: Add and commit	
        run: |
          git add .	
          git config user.name "Automated"	
          git config user.email "actions@users.noreply.github.com"	
          git commit -m "Latest data" 	
      - name: Push	
        run: git push
